name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Java 21のセットアップ
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: テストを実行
        run: |
          chmod +x mvnw
          ./mvnw test